#!/bin/sh

if [ -z ${DEPLOYFROM+x} ]; then
	DEPLOYFROM=/home/aercon/kernel-boot
fi;

mv /boot/uImage /boot/uImage.old
cp $DEPLOYFROM/uImage /boot
cp $DEPLOYFROM/imx6q-ts4900-2.dtb /boot
cp $DEPLOYFROM/imx6q-ts4900-2.dtb /boot/imx6q-ts4900-3f.dtb
