#!/bin/bash

if [ -z ${USER+x} ]; then
	USER=aercon
fi;

ssh $USER@$1 "mkdir ~/kernel-boot; mkdir ~/kernel-deploy"

cd ~/kernel-staging
scp boot/uImage boot/imx6*-ts4900-*.dtb $USER@$1:~/kernel-boot
scp ~/kernel-staging/deploy-image $USER@$1:~/kernel-deploy
#scp -r ~/kernel-staging/lib $USER@$1:~/kernel-deploy/